[2023-09-12T18:15:51.218+0000] {processor.py:156} INFO - Started process (PID=8787) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:15:51.220+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:15:51.234+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:15:51.234+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:15:51.466+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:15:51.448+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:15:51.481+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:15:51.540+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.327 seconds
[2023-09-12T18:16:21.783+0000] {processor.py:156} INFO - Started process (PID=8844) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:16:21.785+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:16:21.786+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:16:21.786+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:16:21.853+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:16:21.845+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:16:21.860+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:16:21.896+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.122 seconds
[2023-09-12T18:16:52.274+0000] {processor.py:156} INFO - Started process (PID=8901) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:16:52.277+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:16:52.278+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:16:52.278+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:16:52.371+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:16:52.363+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:16:52.375+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:16:52.436+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.166 seconds
[2023-09-12T18:17:22.538+0000] {processor.py:156} INFO - Started process (PID=8958) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:17:22.542+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:17:22.543+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:17:22.543+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:17:22.682+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:17:22.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:17:22.695+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:17:22.751+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.212 seconds
[2023-09-12T18:17:53.345+0000] {processor.py:156} INFO - Started process (PID=9015) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:17:53.347+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:17:53.349+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:17:53.348+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:17:53.440+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:17:53.425+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:17:53.446+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:17:53.506+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.173 seconds
[2023-09-12T18:18:24.124+0000] {processor.py:156} INFO - Started process (PID=9072) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:18:24.126+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:18:24.127+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:18:24.127+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:18:24.206+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:18:24.167+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:18:24.225+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:18:24.298+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.177 seconds
[2023-09-12T18:18:54.468+0000] {processor.py:156} INFO - Started process (PID=9129) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:18:54.471+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:18:54.475+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:18:54.474+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:18:54.521+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:18:54.513+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:18:54.525+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:18:54.581+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.118 seconds
[2023-09-12T18:19:25.532+0000] {processor.py:156} INFO - Started process (PID=9186) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:19:25.554+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:19:25.556+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:19:25.555+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:19:25.624+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:19:25.611+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:19:25.627+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:19:25.681+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.152 seconds
[2023-09-12T18:19:56.182+0000] {processor.py:156} INFO - Started process (PID=9243) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:19:56.186+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:19:56.188+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:19:56.188+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:19:56.248+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:19:56.232+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:19:56.251+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:19:56.299+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.125 seconds
[2023-09-12T18:20:26.629+0000] {processor.py:156} INFO - Started process (PID=9301) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:20:26.631+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:20:26.633+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:20:26.633+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:20:26.723+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:20:26.708+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:20:26.727+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:20:26.793+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.174 seconds
[2023-09-12T18:20:57.730+0000] {processor.py:156} INFO - Started process (PID=9358) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:20:57.732+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:20:57.733+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:20:57.733+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:20:57.787+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:20:57.778+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:20:57.811+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:20:57.846+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.121 seconds
[2023-09-12T18:21:28.253+0000] {processor.py:156} INFO - Started process (PID=9415) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:21:28.255+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:21:28.256+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:21:28.256+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:21:28.340+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:21:28.324+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:21:28.343+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:21:28.391+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.142 seconds
[2023-09-12T18:21:58.756+0000] {processor.py:156} INFO - Started process (PID=9472) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:21:58.758+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:21:58.759+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:21:58.759+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:21:58.811+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:21:58.803+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:21:58.814+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:21:58.856+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.105 seconds
[2023-09-12T18:22:29.646+0000] {processor.py:156} INFO - Started process (PID=9527) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:22:29.649+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:22:29.654+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:22:29.653+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:22:29.729+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:22:29.713+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:22:29.742+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:22:29.791+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.162 seconds
[2023-09-12T18:23:00.828+0000] {processor.py:156} INFO - Started process (PID=9579) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:23:00.845+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:23:00.863+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:23:00.862+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:23:01.137+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:23:01.080+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:23:01.153+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:23:01.212+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.387 seconds
[2023-09-12T18:23:31.778+0000] {processor.py:156} INFO - Started process (PID=9637) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:23:31.790+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:23:31.792+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:23:31.792+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:23:31.845+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:23:31.827+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:23:31.848+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:23:31.924+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.150 seconds
[2023-09-12T18:24:02.320+0000] {processor.py:156} INFO - Started process (PID=9694) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:24:02.321+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:24:02.323+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:24:02.322+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:24:02.404+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:24:02.371+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:24:02.407+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:24:02.508+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.196 seconds
[2023-09-12T18:24:33.060+0000] {processor.py:156} INFO - Started process (PID=9751) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:24:33.070+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:24:33.072+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:24:33.072+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:24:33.120+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:24:33.111+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:24:33.124+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:24:33.170+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.114 seconds
[2023-09-12T18:25:03.597+0000] {processor.py:156} INFO - Started process (PID=9809) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:25:03.601+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:25:03.604+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:25:03.603+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:25:03.981+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:25:03.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:25:03.995+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:25:04.064+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.472 seconds
[2023-09-12T18:25:34.640+0000] {processor.py:156} INFO - Started process (PID=9866) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:25:34.646+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:25:34.647+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:25:34.647+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:25:34.815+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:25:34.780+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:25:34.831+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:25:35.000+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.384 seconds
[2023-09-12T18:26:05.109+0000] {processor.py:156} INFO - Started process (PID=9922) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:26:05.111+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:26:05.112+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:26:05.112+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:26:05.199+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:26:05.191+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:26:05.203+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:26:05.248+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.143 seconds
[2023-09-12T18:26:35.312+0000] {processor.py:156} INFO - Started process (PID=9979) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:26:35.314+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:26:35.316+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:26:35.315+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:26:35.362+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:26:35.347+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:26:35.366+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:26:35.399+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.094 seconds
[2023-09-12T18:27:05.719+0000] {processor.py:156} INFO - Started process (PID=10037) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:27:05.720+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:27:05.722+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:27:05.721+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:27:05.761+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:27:05.751+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:27:05.764+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:27:05.814+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.100 seconds
[2023-09-12T18:27:36.547+0000] {processor.py:156} INFO - Started process (PID=10094) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:27:36.562+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:27:36.580+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:27:36.572+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:27:36.773+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:27:36.756+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:27:36.776+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:27:36.832+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.290 seconds
[2023-09-12T18:28:07.322+0000] {processor.py:156} INFO - Started process (PID=10151) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:28:07.324+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:28:07.325+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:28:07.325+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:28:07.406+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:28:07.360+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:28:07.410+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:28:07.474+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.166 seconds
[2023-09-12T18:28:38.003+0000] {processor.py:156} INFO - Started process (PID=10208) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:28:38.004+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:28:38.005+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:28:38.005+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:28:38.135+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:28:38.070+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:28:38.139+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:28:38.174+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.175 seconds
[2023-09-12T18:29:08.800+0000] {processor.py:156} INFO - Started process (PID=10265) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:29:08.802+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:29:08.803+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:29:08.803+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:29:08.842+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:29:08.834+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:29:08.850+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:29:08.914+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.117 seconds
[2023-09-12T18:29:39.566+0000] {processor.py:156} INFO - Started process (PID=10323) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:29:39.568+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:29:39.577+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:29:39.577+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:29:39.634+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:29:39.609+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:29:39.637+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:29:39.675+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.113 seconds
[2023-09-12T18:30:10.548+0000] {processor.py:156} INFO - Started process (PID=10379) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:30:10.551+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:30:10.552+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:30:10.552+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:30:10.593+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:30:10.583+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:30:10.596+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:30:10.631+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.086 seconds
[2023-09-12T18:30:41.474+0000] {processor.py:156} INFO - Started process (PID=10436) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:30:41.475+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:30:41.488+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:30:41.481+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:30:41.601+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:30:41.590+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:30:41.621+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:30:41.689+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.226 seconds
[2023-09-12T18:31:11.971+0000] {processor.py:156} INFO - Started process (PID=10493) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:31:11.972+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:31:11.973+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:31:11.973+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:31:12.018+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:31:12.010+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:31:12.021+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:31:12.090+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.123 seconds
[2023-09-12T18:31:42.767+0000] {processor.py:156} INFO - Started process (PID=10550) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:31:42.774+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:31:42.776+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:31:42.776+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:31:42.846+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:31:42.838+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:31:42.849+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:31:42.917+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.154 seconds
[2023-09-12T18:32:13.053+0000] {processor.py:156} INFO - Started process (PID=10607) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:32:13.055+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:32:13.056+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:32:13.056+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:32:13.099+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:32:13.090+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:32:13.108+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:32:13.155+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.106 seconds
[2023-09-12T18:32:43.652+0000] {processor.py:156} INFO - Started process (PID=10670) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:32:43.653+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:32:43.655+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:32:43.654+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:32:43.694+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:32:43.686+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:32:43.697+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:32:43.735+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.096 seconds
[2023-09-12T18:33:14.736+0000] {processor.py:156} INFO - Started process (PID=10728) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:33:14.737+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:33:14.739+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:33:14.738+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:33:14.819+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:33:14.804+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:33:14.822+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:33:14.860+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.127 seconds
[2023-09-12T18:33:45.434+0000] {processor.py:156} INFO - Started process (PID=10785) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:33:45.449+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:33:45.451+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:33:45.451+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:33:45.601+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:33:45.582+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:33:45.608+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:33:45.690+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.260 seconds
[2023-09-12T18:34:15.973+0000] {processor.py:156} INFO - Started process (PID=10842) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:34:15.975+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:34:15.976+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:34:15.976+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:34:16.060+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:34:16.049+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:34:16.064+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:34:16.101+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.131 seconds
[2023-09-12T18:34:46.734+0000] {processor.py:156} INFO - Started process (PID=10899) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:34:46.735+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:34:46.737+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:34:46.737+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:34:46.785+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:34:46.776+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:34:46.789+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:34:46.824+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.094 seconds
[2023-09-12T18:35:17.513+0000] {processor.py:156} INFO - Started process (PID=10956) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:35:17.515+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:35:17.516+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:35:17.516+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:35:17.555+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:35:17.547+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:35:17.558+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:35:17.598+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.088 seconds
[2023-09-12T18:35:48.053+0000] {processor.py:156} INFO - Started process (PID=11013) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:35:48.054+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:35:48.056+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:35:48.055+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:35:48.175+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:35:48.116+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:35:48.178+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:35:48.218+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.170 seconds
[2023-09-12T18:36:18.495+0000] {processor.py:156} INFO - Started process (PID=11065) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:36:18.507+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:36:18.524+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:36:18.524+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:36:18.593+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:36:18.586+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:36:18.596+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:36:18.696+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.209 seconds
[2023-09-12T18:36:49.564+0000] {processor.py:156} INFO - Started process (PID=11123) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:36:49.568+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:36:49.570+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:36:49.570+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:36:49.680+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:36:49.649+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:36:49.684+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:36:49.739+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.179 seconds
[2023-09-12T18:37:19.885+0000] {processor.py:156} INFO - Started process (PID=11180) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:37:19.886+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:37:19.888+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:37:19.887+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:37:19.964+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:37:19.925+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:37:19.968+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:37:20.019+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.142 seconds
[2023-09-12T18:37:50.277+0000] {processor.py:156} INFO - Started process (PID=11237) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:37:50.278+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:37:50.280+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:37:50.279+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:37:50.347+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:37:50.339+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:37:50.351+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:37:50.404+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.136 seconds
[2023-09-12T18:38:20.544+0000] {processor.py:156} INFO - Started process (PID=11294) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:38:20.545+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:38:20.551+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:38:20.550+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:38:20.598+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:38:20.582+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:38:20.602+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:38:20.637+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.097 seconds
[2023-09-12T18:38:51.445+0000] {processor.py:156} INFO - Started process (PID=11352) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:38:51.447+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:38:51.448+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:38:51.448+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:38:51.508+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:38:51.493+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:38:51.512+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:38:51.554+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.112 seconds
[2023-09-12T18:39:21.685+0000] {processor.py:156} INFO - Started process (PID=11409) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:39:21.696+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:39:21.697+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:39:21.697+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:39:21.760+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:39:21.745+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:39:21.764+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:39:21.818+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.138 seconds
[2023-09-12T18:39:52.679+0000] {processor.py:156} INFO - Started process (PID=11467) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:39:52.680+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:39:52.682+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:39:52.682+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:39:52.739+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:39:52.724+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:39:52.743+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:39:52.800+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.125 seconds
[2023-09-12T18:40:23.171+0000] {processor.py:156} INFO - Started process (PID=11524) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:40:23.173+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:40:23.175+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:40:23.174+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:40:23.219+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:40:23.210+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:40:23.224+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:40:23.292+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.125 seconds
[2023-09-12T18:40:54.283+0000] {processor.py:156} INFO - Started process (PID=11583) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:40:54.284+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:40:54.286+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:40:54.286+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:40:54.334+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:40:54.321+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:40:54.338+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:40:54.390+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.119 seconds
[2023-09-12T18:41:24.971+0000] {processor.py:156} INFO - Started process (PID=11640) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:41:24.973+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:41:24.974+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:41:24.974+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:41:25.083+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:41:25.074+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:41:25.087+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:41:25.125+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.158 seconds
[2023-09-12T18:41:55.679+0000] {processor.py:156} INFO - Started process (PID=11698) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:41:55.681+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:41:55.682+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:41:55.682+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:41:55.731+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:41:55.717+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:41:55.735+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:41:55.774+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.100 seconds
[2023-09-12T18:42:26.084+0000] {processor.py:156} INFO - Started process (PID=11755) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:42:26.086+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:42:26.087+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:42:26.087+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:42:26.177+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:42:26.168+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:42:26.181+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:42:26.221+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.141 seconds
[2023-09-12T18:42:56.293+0000] {processor.py:156} INFO - Started process (PID=11809) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:42:56.309+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:42:56.311+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:42:56.311+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:42:56.424+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:42:56.415+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:42:56.428+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:42:56.536+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.247 seconds
[2023-09-12T18:43:26.679+0000] {processor.py:156} INFO - Started process (PID=11866) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:43:26.680+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:43:26.682+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:43:26.681+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:43:26.787+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:43:26.757+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:43:26.806+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:43:26.853+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.178 seconds
[2023-09-12T18:43:57.046+0000] {processor.py:156} INFO - Started process (PID=11921) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:43:57.048+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:43:57.049+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:43:57.049+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:43:57.160+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:43:57.137+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:43:57.163+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:43:57.212+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.170 seconds
[2023-09-12T18:44:27.450+0000] {processor.py:156} INFO - Started process (PID=11978) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:44:27.452+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:44:27.486+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:44:27.473+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:44:27.551+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:44:27.536+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:44:27.555+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:44:27.633+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.196 seconds
[2023-09-12T18:44:57.900+0000] {processor.py:156} INFO - Started process (PID=12033) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:44:57.903+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:44:57.920+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:44:57.920+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:44:57.961+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:44:57.953+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:44:57.964+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:44:58.003+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.112 seconds
[2023-09-12T18:45:28.448+0000] {processor.py:156} INFO - Started process (PID=12091) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:45:28.460+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:45:28.462+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:45:28.461+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:45:28.529+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:45:28.505+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:45:28.532+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:45:28.571+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.127 seconds
[2023-09-12T18:45:58.939+0000] {processor.py:156} INFO - Started process (PID=12143) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:45:58.941+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:45:58.942+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:45:58.942+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:45:58.995+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:45:58.978+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:45:59.018+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:45:59.060+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.129 seconds
[2023-09-12T18:46:29.231+0000] {processor.py:156} INFO - Started process (PID=12200) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:46:29.232+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:46:29.242+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:46:29.242+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:46:29.325+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:46:29.273+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:46:29.328+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:46:29.391+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.164 seconds
[2023-09-12T18:46:59.731+0000] {processor.py:156} INFO - Started process (PID=12258) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:46:59.733+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:46:59.751+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:46:59.751+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:46:59.799+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:46:59.790+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:46:59.805+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:46:59.861+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.133 seconds
[2023-09-12T18:47:29.959+0000] {processor.py:156} INFO - Started process (PID=12315) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:47:29.961+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:47:29.972+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:47:29.971+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:47:30.040+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:47:30.022+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:47:30.044+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:47:30.110+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.163 seconds
[2023-09-12T18:48:00.967+0000] {processor.py:156} INFO - Started process (PID=12370) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:48:00.970+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:48:00.998+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:48:00.985+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:48:01.129+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:48:01.097+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:48:01.142+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:48:01.311+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.390 seconds
[2023-09-12T18:48:34.712+0000] {processor.py:156} INFO - Started process (PID=12425) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:48:34.728+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:48:34.739+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:48:34.739+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:48:35.092+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:48:35.033+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:48:35.109+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:48:35.245+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.555 seconds
[2023-09-12T18:49:06.137+0000] {processor.py:156} INFO - Started process (PID=12479) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:49:06.153+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:49:06.156+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:49:06.156+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:49:06.459+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:49:06.402+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:49:06.476+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:49:06.594+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.476 seconds
[2023-09-12T18:49:38.334+0000] {processor.py:156} INFO - Started process (PID=12533) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:49:38.345+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:49:38.348+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:49:38.348+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:49:38.669+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:49:38.621+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:49:38.685+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:49:38.838+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.524 seconds
[2023-09-12T18:50:09.276+0000] {processor.py:156} INFO - Started process (PID=12590) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:50:09.289+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:50:09.292+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:50:09.292+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:50:09.417+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:50:09.387+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:50:09.425+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:50:09.583+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.335 seconds
[2023-09-12T18:50:39.879+0000] {processor.py:156} INFO - Started process (PID=12646) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:50:39.892+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:50:39.895+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:50:39.894+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:50:40.047+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:50:39.989+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:50:40.059+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:50:40.139+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.276 seconds
[2023-09-12T18:51:10.541+0000] {processor.py:156} INFO - Started process (PID=12702) to work on /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:51:10.544+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/script/sceduler.py for tasks to queue
[2023-09-12T18:51:10.547+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:51:10.546+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:51:10.741+0000] {logging_mixin.py:149} INFO - [2023-09-12T18:51:10.686+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/script/sceduler.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/script/sceduler.py", line 30, in <module>
    pg_hook = PostgresHook(postgres_conn_id='postgres_default')
NameError: name 'PostgresHook' is not defined
[2023-09-12T18:51:10.759+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/script/sceduler.py
[2023-09-12T18:51:10.880+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/script/sceduler.py took 0.359 seconds
